### PR TITLE
Fixing typos in COWL specification

### PR DESCRIPTION
**Pull request by jonathanKingston**
@deian little nervous about the number of changes bikeshed has made here however some of the references have changed due to typos so that could be it.

Let me know if there is any issue with this etc.

### CODE REVIEW

**Comment by jonathanKingston** [comment]
I'm going to push error fixes for bikeshed next; I'll add to this pull I think.

**Comment by deian** [comment]
@jonathanKingston thanks! I should've given you a heads up since I was just prepping this for a PR, but got stuck without wifi on my flight to europe. I've been addressing the bikeshed errors, rebasing and squashing everything. I'll merge everything on top of this.

**Comment by jonathanKingston** [comment]
@deian yeah sorry I have not replied to your mail either; I figured you were busy on holiday or something :D.

I hope this isn't going to be a nightmare to merge together sorry. (It was worthwhile for me whilst I was reading the spec anyway)

**Comment by jonathanKingston** [comment]
I just pushed the bikeshed fixes, I can remove that one if it is a pain to fix the merge there (It may straight merge over the top though as it's only white space mostly).

**Comment by deian** [comment]
Thanks. I'm just merging these manually since I fixed some types on the flight as well. Do you happen to remember the fix for these 2?

```
FATAL ERROR: No 'idl-name' refs found for 'FreshPrivilege'.
FATAL ERROR: No 'idl-name' refs found for 'object'
```

**Comment by jonathanKingston** [comment]
@deian I didn't get round to fixing those, just the ones at the top for markdown syntax errors. My webidl isn't great still :(

Looks to me like object should be ignored from this: https://github.com/tabatkins/bikeshed/issues/381

The other looks like it needs to be defined here:

```
<pre class="idl">
      interface FreshPrivledge {
      }

      [Constructor, NamedConstructor=FreshPrivilege, Exposed=Window, Worker]
```

**Comment by deian** [comment]
Alright. All done. Thank you so much for this!
https://github.com/w3c/webappsec/pull/466

**Pull request closed without merging**
